### ISSUE TITLE
3 finger gesture not working

### ISSUE THREAD

**Issue by OlegKrikun** [mpiannucci/gnome-shell-extended-gestures#10]
3 finger gesture not working on UbuntuGnome 17.04 (Wayland) =(

**Comment by mpiannucci** [comment]
What is your laptop?

**Comment by OlegKrikun** [comment]
Dell XPS 15 9560 
UbuntuGnome 17.04 (4.12.0-041200-generic #201707022031)

**Comment by mpiannucci** [comment]
That should work. Make sure you are running a Wayland session, it will not work in X

**Comment by OlegKrikun** [comment]
```
oleg@xps:~$ echo $XDG_SESSION_TYPE
wayland
```

**Comment by mpiannucci** [comment]
I will look into it later today, thanks for letting me know

**Comment by OlegKrikun** [comment]
Thanks for you work =) Let me known if i can help =)

**Comment by OlegKrikun** [comment]
I uninstalled [libinput-gestures](https://github.com/bulletmark/libinput-gestures).
Now extension work as expected =)
(libinput-gestures was stopped when i test this extension)
