### ISSUE TITLE
Not working on my laptop, Please help me~

### ISSUE THREAD

**Issue by BetterLuke** [mpiannucci/gnome-shell-extended-gestures#13]
My laptop is DELL XPS 9360, my touchpad support multiple gestrue, But this extension is not working now. Could you have some method to solve it?

**Comment by BetterLuke** [comment]
I see your note is "only working in Wayland session"，so how make it working?

**Comment by mpiannucci** [comment]
Are you logged into a Wayland Session?

**Comment by BetterLuke** [comment]
Oh I get it. After I install Gnome-Wayland, Everything is perfect !  My release is Ubuntu17.04 that default session is xorg, so I hope you update your README to let more people know adout it like my situation. Cheers!

**Comment by BetterLuke** [comment]
Your are genius! you make Linux more charm!

**Comment by mpiannucci** [comment]
Youre welcome!
