### ISSUE TITLE
Add XOrg support

### ISSUE THREAD

**Issue by paveltrufi** [mpiannucci/gnome-shell-extended-gestures#20]
As I can read in the README, running a Wayland session is a requirement in order to use this extension.

I am facing some problems with Wayland at the day (for example GParted doesn't start-up with it) so I can't use it until it gets truly stable.

Thanks in advance.

**Comment by mpiannucci** [comment]
Unfortunately I am not sure if this is possible. I am pretty sure that the GNOME shell gestures don't work on XORG sessions, which means that this extension cannot work either. I can check for sure when Fedora 27 drops this week!

**Comment by mpiannucci** [comment]
Justed tested the built in gestures with Fedora 27 using Xorg and there was nothing. 

Sorry but this extension is restricted to Wayland because it is locked with what Gnome can handle out the of the box.
