### ISSUE TITLE
Cycle Applications - display open apps 

### ISSUE THREAD

**Issue by lpalazzi** [mpiannucci/gnome-shell-extended-gestures#25]
The Cycle Applications gesture only cycles between the most recently focused application. It would be nice if when you cycle applications using the gesture it displayed all open applications (like when you use Alt+Tab)  and you could swipe to the one you want to switch to.

**Comment by mpiannucci** [comment]
Yeah that was my original intention because that's what Windows does and its nice. However, it is non trivial to get that up and running in gnome because of how the gestures work compared wiht windows and macos for now. 

I will keep this on my radar and hopefully get around to messing with it.

**Comment by PlugaruT** [comment]
For me, horizontal 3 finger move most often is interpreted as vertical movement. Maybe improve the way this gestures are detected :/

**Comment by mpiannucci** [comment]
Are you using the master version or the one from the Gnome Extension Store? 

That has been fixed recently but I have not submitted an official update yet

**Comment by PlugaruT** [comment]
I am using the one from store. But I think I will switch to the version from GitHub.

**Comment by PlugaruT** [comment]
And I can confirm that the latest version is way much better. Thanks a lot for your work.
