### ISSUE TITLE
3 finger vertical action also applied to horizontal gesture

### ISSUE THREAD

**Issue by hackel** [mpiannucci/gnome-shell-extended-gestures#30]
It seems that the 3 Finger Horizontal Gesture will only activate what the 3 Finger Vertical Gesture is set to.  Currently I have Horizontal set to Cycle Applications and Horizontal to Toggle Overview, but swiping in either direction causes the overview to be shown.  If I switch the vertical gesture to cycle applications, both directions cycle applications.

I've just installed the extension on Ubuntu 17.10 (Gnome Shell 3.26.2) on a Dell XPS 13.

**Comment by mpiannucci** [comment]
Sorry about that bug. 

It has been fixed on the master branch but the update is still waiting to be approved on the store. Hopefully it is pushed through soon or you can install manually. 

Thanks!
