### ISSUE TITLE
Dell XPS 15 (9560) hard to trigger

### ISSUE THREAD

**Issue by flyingrub** [mpiannucci/gnome-shell-extended-gestures#33]
`const MOTION_THRESHOLD = 20;` work best for the xps 15. Also the horizontal swipe is harder to trigger than the vertical one.

**Comment by mpiannucci** [comment]
Are you testing from the latest master? 

Its weird because 50 is the same motion threshold that gnome themselves is using.

**Comment by flyingrub** [comment]
Yup I'm testing from master.

**Comment by mpiannucci** [comment]
Thanks for letting me know 20 works best. Gunna try and add a simple settings today to wrangle this issue

**Comment by mpiannucci** [comment]
Gunna continue work on this in #19 . Gunna close in favor of that one.
