### ISSUE TITLE
Extension doesn't work on ThinkPad X1 Carbon Ubuntu 17.10 Gnome shell 3.26.1

### ISSUE THREAD

**Issue by milind-utsav** [mpiannucci/gnome-shell-extended-gestures#36]
Installed from GitHub master branch. Four finger swipe up works out of the box. Extension settings appear in Gnome Tweaks, but no effect on enabling/changing the settings.

**Comment by mpiannucci** [comment]
Are you using wayland?

**Comment by milind-utsav** [comment]
Yes, using Wayland.

**Comment by blamarvt** [comment]
Same issue with same hardware here. What can I provide to help debug?

**Comment by mpiannucci** [comment]
The best way to debug is probably to clone the repo and add some debug prints to make sure gestures are being seen at all.

After you add in the code to add debug logs, then you can install using the script and relaunch your shell session to check if the prints are appearing in the log. 

Not an super easy debug unfortunately.

**Comment by jkehler** [comment]
I'm also having a sensitivity problem on my Spectre x360. I have to basically drag my 3 fingers from the very bottom edge of the trackpad to the very top edge of the trackpad for the gesture to trigger. Very annoying and definitely need some sort of sensitivity adjustment options.

**Comment by mpiannucci** [comment]
Alright definitely sounds like a common issue. I will try to add something in the coming week.

**Comment by mpiannucci** [comment]
Please see #19. There is a description for whats happening and description of the new settings available to change the sensitivity. 

I need testers though!! So if someone can test the setting on master that would be great.
