### ISSUE TITLE
With Drive proprity NVIDIA not works

### ISSUE THREAD

**Issue by ghost** [mpiannucci/gnome-shell-extended-gestures#39]
Hello,

When I use the NVIDIA video drive it does not work.
When I use the X.org drive it is working normally.
But does anyone have this problem?

**Comment by mpiannucci** [comment]
I am not sure if NVIDIA works with wayland yet so there may be issues with this plugin becasue wayland is required

**Comment by pqL4** [comment]
Do you want me to run some command here for you to check my configurations?
Could you help me ?

**Comment by mpiannucci** [comment]
can you tell me the output of `echo $XDG_SESSION_TYPE`?

**Comment by dmattox10** [comment]
For me, the result of that command is "x11?"

**Comment by mpiannucci** [comment]
That means that you are not running Wayland so the extension will not work
unfortunately.
