### ISSUE TITLE
Feature request: 3 finger swipe Back / Forward

### ISSUE THREAD

**Issue by glebm** [mpiannucci/gnome-shell-extended-gestures#41]
Hi, it'd be really nice to be able to configure 3-finger swipe to go forwards / backwards (e.g. in a browser).

**Comment by flyingrub** [comment]
We could trigger it thanks to the keyboard shortcut : https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_navigation

**Comment by rmader** [comment]
I guess this would require adding some kind of virtual keyboard, similar to the on screen keyboard. Will also have a look into this.

**Comment by jounathaen** [comment]
I used Fusama, and with xdotool it was sufficient to send `ALT+LEFT/RIGHT` to most applications.

**Comment by mpiannucci** [comment]
Hi all, please look at the pull request here https://github.com/mpiannucci/gnome-shell-extended-gestures/pull/55 This shows how you can use custom key combos, but I have not had time to generalize for and made a gui yet.

**Comment by glebm** [comment]
@mpiannucci That looks good already. I don't really need custom commands, I think back/forward is the majority use-case anyhow.

**Comment by mpiannucci** [comment]
I have merged this functionality into master. You can use the master branch until an update is pushed to the plugin store
