### ISSUE TITLE
Custom Key Binds for a Gesture

### ISSUE THREAD

**Issue by badoughatcher** [mpiannucci/gnome-shell-extended-gestures#43]
Would love to be able to bind three-finger swipe down to a custom key binding. I would use this to close browser tabs with CTRL+W. This would dramatically improve the customization and usefulness of this already awesome extension.

**Comment by mpiannucci** [comment]
Thanks I really want this too and a bunch of people have requested it. I will comment back on here when I figure out how to add it robustly!

**Comment by mpiannucci** [comment]
Merging this in with #11 THanks!
