### ISSUE TITLE
Support for ubuntu 18.04

### ISSUE THREAD

**Issue by zrothberg** [mpiannucci/gnome-shell-extended-gestures#45]
So my understanding is this doesn't work for 18.04. Is there plans to support this or is there a way to get it running on 18.04.

**Comment by mpiannucci** [comment]
I thought it worked still. What version of gnome do you have?

**Comment by hackel** [comment]
Ubuntu 18.04 defaults to Xorg again.

**Comment by mpiannucci** [comment]
BUmmer. I dont think this will ever work on Xorg unless GNOME changes their stuff to work on xorg as well (Which is doubtful). Sorry!

**Comment by mpiannucci** [comment]
You can also use wayland on 18.04, it just isnt the default

**Comment by zrothberg** [comment]
Sorry Lost track of this. I am using wayland. Gnome verison 3.28.2
