### ISSUE TITLE
Feature Request: Support for Xorg

### ISSUE THREAD

**Issue by cbwang2016** [mpiannucci/gnome-shell-extended-gestures#46]
Ubuntu would use Xorg after 18.04. Could you please add support for this?

**Comment by mpiannucci** [comment]
No. This will only ever work for wayland because GNOME only allows the feature on wayland sessions. Sorry!

**Comment by cbwang2016** [comment]
Thanks. So is there anyway else to use gesture in Xorg? like a shell script or something?
