### ISSUE TITLE
Switch workspaces doesn't work

### ISSUE THREAD

**Issue by usbkey9** [mpiannucci/gnome-shell-extended-gestures#58]
Hi guys,

Switch workspaces feature doesn't work neither 3 nor 4 fingers

Ubuntu 18.10
Wayland

Best

**Comment by mpiannucci** [comment]
which version of gnome are you running? Which laptop are you using

**Comment by usbkey9** [comment]
Ubuntu's default gnome version (3.30.1)
Asus laptop

**Comment by mpiannucci** [comment]
The master branch works with 3.30 but it has not been updated on the extension store yet. So if you install from master it will work

**Comment by usbkey9** [comment]
Works fine, thanks
