### ISSUE TITLE
Not working on Ubuntu 18.04 Thinkpad T510

### ISSUE THREAD

**Issue by rhr407** [mpiannucci/gnome-shell-extended-gestures#61]

**Comment by mpiannucci** [comment]
Are you running wayland?

**Comment by rhr407** [comment]
I used the following command to check and it responded with 'x11'

echo $XDG_SESSION_TYPE

**Comment by mpiannucci** [comment]
This extension only works with Wayland so thats why its not working

**Comment by mpiannucci** [comment]
Closing becasue this was a wayland problem. If you are using wayland and still have this issue please let me know
