### ISSUE TITLE
Display Wayland requirement in extensions.gnome.org

### ISSUE THREAD

**Issue by olibre** [mpiannucci/gnome-shell-extended-gestures#67]
Thank you very much for your working and productive GNOME extension :-D 

But in another computer I was using GNOME Xorg because I wanted to locate my mouse pointer using the Ctrl key (this can be enabled in Tweaks but this is working only with Xorg). I spent some time before figuring it was an issue with the Wayland requirement.

Please add a warning about Wayland requirement in https://extensions.gnome.org/extension/1253/extended-gestures/  You may also indicate explicitly **it does not work with GNOME Xorg**.

**Comment by rmader** [comment]
+1 for this one. Just one more line in the description so all the Ubuntu users still on X11 by default know what they need to do (and might be even encouraged to switch to the Wayland session, which generally is a good thing).

**Comment by mpiannucci** [comment]
Thank you!!! Updated the description here https://extensions.gnome.org/extension/1253/extended-gestures
