### ISSUE TITLE
[Fedora 31] It is not working

### ISSUE THREAD

**Issue by azazello4** [mpiannucci/gnome-shell-extended-gestures#72]
It seems it does not work on my Fedora 31 installation (Thinkpad T460).
4-fingers-swipe works fine, 3-fingers-swipe does nothing.
Other active extensions:

- Application Menu
- Caffeine
- Dash to Dock
- Freon
- Gsconnect
- Gnomesome
- Kstatusnotifieritem
- User themes
- System-monitor

If I enable the extension, then logout-login, the extension is disabled.

**Comment by BjoernDaase** [comment]
Hmm, for me on F31 it works perfectly fine...

**Comment by azazello4** [comment]
Yeah it started working fine after a while. Closing this.
