### ISSUE TITLE
Installation reports "ERROR" on Gnome 3.36

### ISSUE THREAD

**Issue by mbidewell** [mpiannucci/gnome-shell-extended-gestures#83]
When installing this extension on Fedora 32 with Gnome 3.36.  The install is marked as "ERROR" extension still works however.

**Comment by asen-d** [comment]
> When installing this extension on Fedora 32 with Gnome 3.36. The install is marked as "ERROR" extension still works however.

I have the same with Manjaro and Gnome 3.36

**Comment by ComputeAllTheThings** [comment]
```
Apr 25 09:41:02 localhost gnome-software[4117]: failed to create an app for user/*/*/shell-extension/extendedgestures_mpiannucci.github.com/*
Apr 25 09:41:02 localhost gnome-software[4117]: gs_app_get_local_file: assertion 'GS_IS_APP (app)' failed
Apr 25 09:41:02 localhost gnome-software[4117]: gs_app_get_metadata_item: assertion 'GS_IS_APP (app)' failed
Apr 25 09:41:02 localhost gnome-software[4117]: gs_details_page_set_app: assertion 'GS_IS_APP (app)' failed

```

**Comment by mpiannucci** [comment]
I will submit a new package to the extension store from master soon. With the latest pull request merged now, install from master should work on 3.36

**Comment by soelkongen** [comment]
The version[ Gnome Extensions ](https://extensions.gnome.org/extension/1253/extended-gestures/)has this error

**Comment by mpiannucci** [comment]
@soelkongen Yes I have submitted an update to the extensions store but it has not been approved yet.
