### ISSUE TITLE
Why only wayland?

### ISSUE THREAD

**Issue by SasukeeUchiha** [mpiannucci/gnome-shell-extended-gestures#87]
Why does it only work with Wayland? It is highly inconvenient as Wayland still has a lot of bugs and it isn't the default for 20.04 LTS.

**Comment by mpiannucci** [comment]
Because of the way the gnome shell works, libinput gestures are only supported when running in wayland mode. Because this is a native gnome extension, it will only work when gnome itself propagates the gestures. 

Sorry for the inconvenience!
