### ISSUE TITLE
Not working - Ubuntu 20.10 and Dell XPS 13 9370

### ISSUE THREAD

**Issue by carlihland** [mpiannucci/gnome-shell-extended-gestures#97]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

$ uname -r
5.8.0-33-generic
carl@carl-XPS-13-9

**Comment by uguntde** [comment]
Same laptop XPS 13 7390, and also doesn't work

$ uname -r
5.8.0-25-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

**Comment by mpiannucci** [comment]
Thanks for the reports. I am waiting for my new Linux laptop to show up then I can try and fix it

**Comment by uguntde** [comment]
Gestrures all work already if you run wayland.

**Comment by dbrimley** [comment]
I can confirm if I switch to Wayland it works, it does not work in default xorg.

Also in Wayland it stops working when I switch to horizontal workspaces (using gnome tweaks), 3 finger swipe only works for vertical workspaces.

I have a Dell XPS 9360 as below..

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

uname -r
5.4.0-58-generic
`

**Comment by mpiannucci** [comment]
Great thanks. Unfortunately gnome hooks some gestures by default and this extension can't over ride them
